### ISSUE TITLE
RF19 -  En el caso de los vendedores ambulantes, el sistema debe permitir que el vendedor indique si esta activo o no.

### ISSUE THREAD

**Issue by LucasCabello** [DCC-CC4401/Pied-Piper#19]

**Comment by gabrielpf7u7** [comment]
El vendedor puede indicar si está activo o no con el atributo "activo:bool" 
Falta implementar cambio en la BdD con boton y display correcto

**Comment by AlonsoReyes** [comment]
Así es,  por lo mismo sigue abierto el issue. ¿Querías decir algo con el comentario o es para dejar más claro como funciona?
